# Generated by Django 4.2.19 on 2025-03-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_tag_unique_tag_tag_unique_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
