# Generated by Django 4.2.19 on 2025-03-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_short_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
        migrations.DeleteModel(
            name='TagInRecipe',
        ),
    ]
