# Generated by Django 4.2.19 on 2025-03-10 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Должно быть не менее 1 минуты!'), django.core.validators.MaxValueValidator(32000, message='Слишком долго!')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть не менее 1!'), django.core.validators.MaxValueValidator(32000, message='Слишком большое количество')], verbose_name='Количество'),
        ),
    ]
